### PR TITLE
Libpitt/166 version col

### PR DESCRIPTION
**Pull request by libpitt**
Change log:
1. Add Revisions column (lazy loads revision data to avoid querying more than necessary in `/datasets/data-status`)
2. Add button to download CSV of data of derived/processed Datasets
3. Remove `descendant_datasets` from main CSV
4. Add entity api env config

Requires:
https://github.com/sennetconsortium/ingest-api/pull/301
https://github.com/hubmapconsortium/ingest-api/pull/502

### CODE REVIEW

**Comment by yuanzhou** [comment]
@bhonick I wanted to confirm with you that you are not using the `descendant_datasets` from the CSV download, are you?

image

**Comment by bhonick** [comment]
@yuanzhou I'm aware of it but am not actively using it for anything.

**Comment by yuanzhou** [comment]
> @yuanzhou I'm aware of it but am not actively using it for anything.

Great! We are removing this column since it may contain a long list of descendants and won't be much help for actual use. We are also adding another CSV download of all the processed datasets which can be more desired.

**Review by maxsibilla — APPROVED** [review]

**Review by yuanzhou — CHANGES_REQUESTED** [review]
@libpitt as we discussed earlier, better to use "processed" instead of "derived" in the labels and also in the code variables for consistency.

In addition, I noticed a few issues and some improvements:

Screenshot 2024-02-26 at 2 24 30 PM


1. In the modal of processed datasets, can we add back the primary dataset hubmap_id/sennet_id? You had this orginally: https://github.com/x-atlas-consortia/data-ingest-board/pull/162#issuecomment-1939463285

- The CSV download icon from the main table is overlapping. 

- The result in the Revision column of the modal doesn't look right. I've explained that it's entirely possible one processed dataset is the version 2 of another processed dataset. The rest of the list are just regular processed datasets with no revisions. But none of the processed datasets in the modal should be a revision of the primary dataset. So we really should NOT use this "Revision" column in the modal. Any thoughts @shirey?

In the CSV download, 

Screenshot 2024-02-26 at 2 38 07 PM

- Use the same time format as "Last Touch" (assuming this is UTC as well) for consistency and it's also much better for sorting in Excel spreadsheet.

- If we decide to remove the "Revision" column in the modal, should also remove from CSV.

**Comment by libpitt** [comment]
@yuanzhou All changes can be made except the time one. I am not controlling the format of the timestamp in the ui table, that's using `date.toLocaleString()`. If I use that for CSV, then another user elsewhere would have different format if they have a different locale. 

As for the one in the CSV, the format of the string determined by `date.toUTCString()`.

So if you're okay with another user elsewhere having a different format when downloading the CSV, I can also use the same `toLocaleString()` method.

**Review by yuanzhou — APPROVED** [review]

**Pull request merged**
