### PR TITLE
Updating data table column to support new dataset_type field. Updatin…

### PR DESCRIPTION
**Pull request by maxsibilla**
…g example.env file to replace data_types with dataset_type

### CODE REVIEW

**Comment by yuanzhou** [comment]
NOTE posted on Slack: 

>This PR will probably have to wait until after the winter recess. On the HuBMAP side, we'll need to fully support this new field in the backend and @DerekFurstPitt will be doing some analysis before we can deprecate the `data_types` and start using `dataset_type` across the board.

BTW @maxsibilla don't resolve the merge conflict for now, the workflow prohibits us from merging `dev-integrate` into your branch. Will get to it when ready.

**Comment by yuanzhou** [comment]
@libpitt I think we are ready to move forward with this PR, can you review the changes too? Derek is on vacation.

**Comment by libpitt** [comment]
@yuanzhou On the SenNet side I am able to run the board locally and see `dataset_type` populated. No issues there. I tried the same for HuBMAP with its ingest-api running from the `dev-integrate` branch. There is an error. Has HM updated to support `dataset_type`?

cc @maxsibilla

**Review by libpitt — APPROVED** [review]
@yuanzhou  @maxsibilla  Working locally on both SenNet and HuBMAP.

**Review by yuanzhou — APPROVED** [review]

**Pull request merged**
