### PR TITLE
Libpitt/151 search

### PR DESCRIPTION
**Pull request by libpitt**
Change log:
1. Resolve search url with `q` param
2. Reduce max chars for `ingest_task` modal

### CODE REVIEW

**Review by maxsibilla — APPROVED** [review]
For SenNet the modal appears for shorter ingest messages and the search query now updates the query parameters in the URL

**Review by yuanzhou — CHANGES_REQUESTED** [review]
I did a quick local test and noticed two things:

1. The close button/icon is overlapping with the modal text. We can remove this close button without making margin or padding tweaks since the OK button closes the modal too.

2. It seems the config doesn't make any difference when more than 24 characters specified. The UI only shows up to 24 chars.


Screenshot 2024-01-30 at 2 09 17 PM


@maxsibilla @libpitt can you also verify in case I don't fully understand the usage?

**Comment by libpitt** [comment]
> I did a quick local test and noticed two things:
> 
> 1. The close button/icon is overlapping with the modal text. We can remove this close button without making margin or padding tweaks since the OK button closes the modal too.
> 2. It seems the config doesn't make any difference when more than 24 characters specified. The UI only shows up to 24 chars.
> 
> Screenshot 2024-01-30 at 2 09 17 PM
> @maxsibilla @libpitt can you also verify in case I don't fully understand the usage?

@yuanzhou The close x button has been hidden.

As for the max char config, it shows more than 24 on my larger screen. Wasn't sure with this if to just give the option of an ideal number for both small and large screen, hence the configuration or do something else.

cc @maxsibilla

**Comment by yuanzhou** [comment]
@libpitt can you post a screenshot of how it looks with more than 24 chars on your large screen? Mine is 14 inch Macbook with standard resolution 1352 x 878. We probably just limit it to a small length to accommodate different sizes. I suspect it has something to do with the column size of the data table component, does it allow us to control the column size?

**Comment by libpitt** [comment]
> @libpitt can you post a screenshot of how it looks with more than 24 chars on your large screen? Mine is 14 inch Macbook with standard resolution 1352 x 878. We probably just limit it to a small length to accommodate different sizes. I suspect it has something to do with the column size of the data table component, does it allow us to control the column size?

Nevermind @yuanzhou  You are right. It's still the same 24 on my 24inch screen; Seems I had a case of bad 'deja vu'. I can remove the config and hard code it if you think that's best.

**Comment by yuanzhou** [comment]
@libpitt We don't need this single column to be configurable because there are other columns face the same display limitation. Looking at another column, it seems the table component controls the column size based on width rather than based on characters.  Can you verify if there's always a tooltip showing the full text when the column cell shows `...`? Maybe that's something being handled internally so we don't even need a modal?

Screenshot 2024-01-31 at 12 52 55 PM

On the other hand, the "Group Name" displays more characters without the text being truncated...

Screenshot 2024-01-31 at 1 00 30 PM

**Review by yuanzhou — APPROVED** [review]

**Pull request merged**
